[build]
  # Build command (not needed for static site)
  command = "echo 'Static site - no build required'"

  # Directory to publish (the public folder contains our static files)
  publish = "public"

  # Redirect all routes to index.html for SPA-like behavior
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build.environment]
  # Node version for any build scripts (if needed later)
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
